apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator
  labels:
    app: calculator-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator-app
  template:
    metadata:
      labels:
        app: calculator-app
    spec:
      containers:
        - name: calculator-app-container
          image: rgupta87/mycalculator:latest
          ports:
            - containerPort: 5000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: calculator-app-svc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  labels:
    app: calculator-app
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: calculator-app
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: calculator-app-svc
# spec:
#   type: LoadBalancer
#   selector:
#     app: calculator-app
#   ports:
#   - port: 80
#     targetPort: 5000
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: calculator-app-svc
#   labels:
#     app: calculator-app
# spec:
#   type: NodePort
#   ports:
#       # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
#     - port: 5000
#       targetPort: 5000
#       nodePort: 30007
#   selector:
#     app: calculator-app  